# This is a basic workflow that is manually triggered

name: GAuth workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Environment to deploy'
        # Default value if no value is explicitly provided
        default: 'Dev'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  auth:
    runs-on: ubuntu-latest

    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    - run: |-
        echo "$GITHUB_WORKSPACE"

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/136304058176/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@centering-river-396816.iam.gserviceaccount.com'
        token_format: 'access_token'
        access_token_lifetime: '300s'
    - run: |-
        echo '${{ steps.auth.outputs.access_token }}'
    - uses: actions/setup-java@v3
      with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '11'
    - uses: actions/setup-node@v3
      with:
        node-version: '14'    
    - run: java -version
    - run: npm install -g apigeelint
    - run: apigeelint -s  /home/runner/work/apigee-cicd/apigee-cicd/hr-api/apiproxy -f codeframe.js
    - run: npm install
    - run: npm test /home/runner/work/apigee-cicd/apigee-cicd/test/unit/*.js
    - run: npm run coverage /home/runner/work/apigee-cicd/apigee-cicd/test/unit/*.j
    - run: mvn -f "$GITHUB_WORKSPACE"/hr-api/pom.xml install -P eval  -Dbearer='${{ steps.auth.outputs.access_token }}' -Dapigee.config.options=update
